Velocity-IIITDWD/iiitdwd_2025

- src/app/(home)/alumni.tsx
- src/app/(home)/announcement-component.tsx
- src/app/(home)/brief-content.tsx
- src/app/(home)/hero.tsx
- src/app/(home)/social-media.tsx
- src/app/(institute)/careers/careers-page.tsx
- src/app/(institute)/tenders/SortSearch.tsx
- src/components/ui/menubar.tsx
- src/components/ui/tabs.tsx
- Navbar colors fixed
- Bento cards rearranged
- Alumni fixed
- Careers and Tenders Search fixed
- Added new careers and announcements on sanity side
> fix: home page changes

- src/app/admission/journey-section.tsx
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> data: financial aid

- src/app/admission/btech/admissionLinkData.ts
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> chore: add prev year cut offs

- src/app/admission/btech/admissionLinkData.ts
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> chore: senate 

- src/app/admission/btech/CutoffRanks-component.tsx
- src/app/admission/btech/admissionLinkData.ts
- src/app/admission/btech/cutoffData.ts
- src/app/admission/btech/page.tsx
- src/app/admission/btech/seatMatrix-component.tsx
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> chore: update admission seat matrix and cutoff

- src/app/(home)/appointment-dialog.tsx
- src/app/(home)/info-section.tsx
- src/components/ui/dialog.tsx
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> feat: book a call with director sir

- src/app/admission/btech/admissionLinkData.ts
- src/app/admission/btech/page.tsx
- src/app/admission/journey-section.tsx
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> fix: admissions page

- src/data/building-committee.ts
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> chore: update building committee

- src/data/website-team.ts
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
- Team Member updated
N/A
> fix: team member updated

- src/app/(home)/hero.tsx
```
[ ] Bugfix
[ ] Feature
[ ] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> chore: test new feature for dynamic images

- src/app/(other)/faq/page.tsx
- src/app/admission/btech/admissionLinkData.ts
- src/app/admission/journey-section.tsx
- src/data/footer-links.ts
- src/data/navigation.ts
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> chore: updated fee links

- src/app/(home)/hero.tsx
- src/app/(other)/faq/page.tsx
- src/app/admission/btech/admissionLinkData.ts
- src/app/admission/journey-section.tsx
- src/data/footer-links.ts
- src/data/navigation.ts
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> chore: Fee details updated

- src/components/layout/footer.tsx
- src/components/layout/header.tsx
- src/data/navigation.ts
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> chore: added files

- src/app/(home)/appointment-dialog.tsx
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> chore: jee form

- src/app/providers/kbar.tsx
- src/data/navigation.ts
- src/data/registrar.ts
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> chore: update registrar image

- src/data/registrar.ts
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> chore: update calendar

- src/app/(other)/annoucements/component.tsx
- src/data/navigation.ts
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> fix: add rolling annoucements section

- src/app/(home)/placement-card.tsx
- src/app/placements/placement-stats.tsx
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> chore: update placemen stats

- src/app/(institute)/careers/careers-page.tsx
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> fix: additional docs added in UI

- src/app/(home)/info-section.tsx
- src/app/admission/btech/admissionLinkData.ts
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> chore: fixes for addmissions

- src/components/academics-components/programCards.tsx
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> fix: majors and minors added

- src/app/(home)/placement-card.tsx
- src/app/placements/placement-stats.tsx
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> chore: update placement stats

- src/app/(home)/hero.tsx
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> chore: add scholarship list in quick links

- src/app/(administration)/chairperson/page.tsx
- src/data/navigation.ts
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> chore: update chairperson message and fees

- src/app/admission/btech/admissionLinkData.ts
```
[ ] Bugfix
[ ] Feature
[x] Release
[ ] Tests
[ ] Other
```
Closes #
-
N/A
> chore: update admission links
